---
abstract: 'Rot13-encode Moose-generated exception messages'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Exception-Rot13
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooseX::Exception::Rot13:
    file: lib/MooseX/Exception/Rot13.pm
    version: 0.001
requires:
  Moose: 2.1102
  Moose::Exception: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-Exception-Rot13/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-Exception-Rot13
  homepage: https://metacpan.org/release/MooseX-Exception-Rot13
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moosex-exception-rot13
version: 0.001
